// Deterministic project scan backing the /init command — analogous to
// Claude Code's /init generating CLAUDE.md, but derived directly from
// package.json/manifest files and the top-level layout rather than an agent
// turn, so it's instant, free, and doesn't depend on model quality.

'use strict';

const fs = require('fs');
const path = require('path');

function readJsonSafe(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

function detectStack(root) {
  const facts = [];

  const pkg = readJsonSafe(path.join(root, 'package.json'));
  if (pkg) {
    facts.push(`Node.js project ("${pkg.name || 'unnamed'}"${pkg.version ? `, v${pkg.version}` : ''}).`);
    if (pkg.scripts) {
      const notable = ['test', 'build', 'lint', 'dev', 'start'].filter((k) => pkg.scripts[k]);
      if (notable.length) facts.push(`Scripts available: ${notable.map((k) => `\`npm run ${k}\``).join(', ')}.`);
    }
    const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
    const frameworks = ['react', 'vue', 'svelte', 'express', 'fastify', 'next', 'vscode', '@modelcontextprotocol/sdk'].filter(
      (d) => deps[d]
    );
    if (frameworks.length) facts.push(`Key dependencies: ${frameworks.join(', ')}.`);
  }

  if (fs.existsSync(path.join(root, 'requirements.txt')) || fs.existsSync(path.join(root, 'pyproject.toml'))) {
    facts.push('Python project (requirements.txt/pyproject.toml present).');
  }
  if (fs.existsSync(path.join(root, 'Cargo.toml'))) facts.push('Rust project (Cargo.toml present).');
  if (fs.existsSync(path.join(root, 'go.mod'))) facts.push('Go project (go.mod present).');

  if (fs.existsSync(path.join(root, 'test')) || fs.existsSync(path.join(root, 'tests')) || fs.existsSync(path.join(root, '__tests__'))) {
    facts.push('Has a dedicated test directory — check it for existing patterns before adding new tests.');
  }
  if (fs.existsSync(path.join(root, '.eslintrc.json')) || fs.existsSync(path.join(root, '.eslintrc.js')) || (pkg?.devDependencies && pkg.devDependencies.eslint)) {
    facts.push('ESLint is configured — run it after edits if possible.');
  }
  if (fs.existsSync(path.join(root, 'tsconfig.json'))) facts.push('TypeScript project (tsconfig.json present).');

  return facts;
}

function topLevelLayout(root) {
  try {
    return fs
      .readdirSync(root, { withFileTypes: true })
      .filter((e) => !['.git', 'node_modules', '.cortex', 'dist', 'build', '.vscode'].includes(e.name))
      .map((e) => (e.isDirectory() ? `${e.name}/` : e.name))
      .sort()
      .slice(0, 40);
  } catch {
    return [];
  }
}

/**
 * @param {string} root workspace root
 * @returns {string} markdown content for .cortexrules
 */
function generateProjectRules(root) {
  const facts = detectStack(root);
  const layout = topLevelLayout(root);
  const readme = fs.existsSync(path.join(root, 'README.md'));

  return `# Project conventions (auto-generated by /init on ${new Date().toISOString().slice(0, 10)})

This file is read by Cortex on every turn. Edit it freely — /init only
overwrites it when you re-run the command.

## Stack
${facts.length ? facts.map((f) => `- ${f}`).join('\n') : '- (could not auto-detect a stack — describe it here manually)'}

## Layout
\`\`\`
${layout.join('\n')}
\`\`\`
${readme ? '\nSee README.md for the full project description.' : ''}

## Working agreement
- Prefer editing existing files over creating new ones.
- Match the existing code style in each file rather than imposing a different one.
- Run the project's test/lint scripts (see above) after non-trivial changes when available.
`;
}

module.exports = { generateProjectRules };
